{
 "title": "WaterQuality",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "zone",
    "label": "Zone",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(\n  bucket: \"waterdistribution\",\n  tag: \"zone\"\n)\n"
    }
   },
   {
    "name": "device_name",
    "label": "Device",
    "query": {
     "query": "from(bucket: \"waterdistribution\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"zone\"] == \"${zone}\")\n  |> keep(columns: [\"device\"])\n  |> distinct(column: \"device\")\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "${device_name} Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Water System Map",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"latitude\" or r._field == \"longitude\" or r._field == \"pH\" or r._field == \"Water_Depth\" or r._field == \"ORP\" or r._field == \"Turbidity\" or r._field == \"Temperature\" or r._field == \"Salinity\")\n  |> filter(fn: (r) => r.type == \"tank\") \n  |> schema.fieldsAsCols()\n  |> group(columns: [\"device\", \"type\", \"zone\", \"tank\"]) \n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> group() \n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"measurement\", \"type\", \"_time\"])\n"
    },
    {
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"latitude\" or r._field == \"longitude\" or r._field == \"pH\" or r._field == \"Flow\" or r._field == \"Salinity\")\n  |> filter(fn: (r) => r.type == \"pipelines\") \n  |> schema.fieldsAsCols()\n  |> group(columns: [\"device\", \"type\", \"zone\", \"tank\"]) // Group by your tags\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> group() // Ungroup to combine all into a single table\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"measurement\", \"type\", \"_time\"])"
    },
    {
     "query": "import \"influxdata/influxdb/schema\"\n\nfrom(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"latitude\" or r._field == \"longitude\" or r._field == \"pH\" or r._field == \"Flow\" or r._field == \"Salinity\")\n  |> filter(fn: (r) => r.device == \"${device_name}\") \n  |> schema.fieldsAsCols()\n  |> group(columns: [\"device\", \"type\", \"zone\", \"tank\"]) // Group by your tags\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> group() // Ungroup to combine all into a single table\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"measurement\", \"type\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Current Values",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"waterdistribution\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r.device == \"${device_name}\")\n  |> filter(fn: (r) => r._field != \"latitude\" and r._field != \"longitude\")"
    }
   ]
  },
  {
   "title": "${device_name} Measurements",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device\"] == \"${device_name}\") // Replace with your device tag value\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") // Convert fields into columns\n  |> drop(columns: [\"latitude\", \"longitude\"]) // Remove latitude and longitude fields\n"
    }
   ]
  },
  { "title": "All Sensor Overview - ${zone}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Flow - All Sensors ${zone}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r[\"zone\"] == \"${zone}\") \n  |> filter(fn: (r) => r[\"_field\"] == \"Flow\") \n  |> group(columns: [\"device\"]) // Group by the device tag"
    }
   ]
  },
  {
   "title": "Salinity - All Sensors ${zone}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r[\"zone\"] == \"${zone}\") \n  |> filter(fn: (r) => r[\"_field\"] == \"Salinity\") \n  |> group(columns: [\"device\"]) // Group by the device tag"
    }
   ]
  },
  {
   "title": "pH - All Sensors ${zone}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r[\"zone\"] == \"${zone}\") \n  |> filter(fn: (r) => r[\"_field\"] == \"pH\") \n  |> group(columns: [\"device\"]) // Group by the device tag"
    }
   ]
  },
  {
   "title": "ORP - All Sensor ${zone}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r[\"zone\"] == \"${zone}\") \n  |> filter(fn: (r) => r[\"_field\"] == \"ORP\") \n  |> group(columns: [\"device\"]) // Group by the device tag"
    }
   ]
  },
  {
   "title": "Water Depth - All Sensor ${zone}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r[\"zone\"] == \"${zone}\") \n  |> filter(fn: (r) => r[\"_field\"] == \"Water_Depth\") \n  |> group(columns: [\"device\"]) // Group by the device tag"
    }
   ]
  },
  {
   "title": "Turbidity - All Sensors ${zone}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r[\"zone\"] == \"${zone}\") \n  |> filter(fn: (r) => r[\"_field\"] == \"Turbidity\") \n  |> group(columns: [\"device\"]) // Group by the device tag"
    }
   ]
  },
  {
   "title": "Temperature - All Sensors ${zone}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
   "targets": [
    {
     "query": "from(bucket: \"waterdistribution\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r[\"zone\"] == \"${zone}\") \n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\") \n  |> group(columns: [\"device\"]) // Group by the device tag"
    }
   ]
  }
 ]
}